Traceback (most recent call last):
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/VictorMagdaleno/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
nwbfile2.acquisition['test_timeseries']
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-11-c7c538c793a6>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mnwbfile2[0m[0;34m.[0m[0macquisition[0m[0;34m[[0m[0;34m'test_timeseries'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/lib/python3.7/site-packages/hdmf/utils.py[0m in [0;36m__getitem__[0;34m(self, args)[0m
[1;32m    886[0m                 [0;32mreturn[0m [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__getitem__[0m[0;34m([0m[0mval[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    887[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 888[0;31m             [0;32mreturn[0m [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__getitem__[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    889[0m [0;34m[0m[0m
[1;32m    890[0m     [0;32mdef[0m [0m__setitem__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mkey[0m[0;34m,[0m [0mvalue[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'test_timeseries'
KeyError: 'test_timeseries'

